TotalService/Controllers/RutaController.cs
using System;
using System.Activities.Statements;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TotalService.Models;
using WebMatrix.WebData;

namespace TotalService.Controllers
{

    public class marker
    {
        public static Random Random = new Random();

        public int Indice { get; set; }

        public decimal Latitud { get; set; }

        public decimal Longitud { get; set; }

        public string NombreMapa { get; set; }
    }

    [Authorize(Roles = Helpers.Comunes.ROL_Administrador + "," + Helpers.Comunes.ROL_Supervisor + "," + Helpers.Comunes.ROL_Operador)]
    public class RutaController : Controller
    {
        private grocusmx_totalserviceEntities db = new grocusmx_totalserviceEntities();

        // GET: /Ruta/
        public ActionResult Index()
        {
            var ope_ruta = db.OPE_Ruta.OrderByDescending(o => o.FechaRuta);

            ViewBag.UsernameTecnico = new SelectList(db.CAT_Usuario, "Username", "Nombre");

            return View(ope_ruta.ToList());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(OPE_Ruta ruta)
        {
            var ope_ruta = 
                db.OPE_Ruta
                .Where(m => m.UsernameTecnico == ruta.UsernameTecnico || string.IsNullOrEmpty(ruta.UsernameTecnico))
                .Where(m => m.FechaRuta == ruta.FechaRuta || ruta.FechaRuta == null || ruta.FechaRuta == DateTime.MinValue)
                .OrderByDescending(o => o.FechaRuta);

            ViewBag.UsernameTecnico = new SelectList(db.CAT_Usuario, "Username", "Nombre");

            return View("Index", ope_ruta.ToList());

        }

        // GET: /Ruta/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            OPE_Ruta oPE_Ruta = null;

            try
            {

                oPE_Ruta =
                    db.OPE_Ruta
                    .Include(o => o.OPE_Visita.Select(v => v.OPE_Visitado))
                    .Include(o => o.OPE_Visita.Select(v => v.OPE_ServicioVisita.Select(s => s.CAT_Servicio)))
                    .Include(o => o.OPE_Visita.Select(v => v.OPE_Devolucion))
                    .Include(o => o.OPE_Visita.Select(v => v.OPE_CheckOut))
                    .Include(o => o.OPE_Visita.Select(v => v.OPE_CheckOutSinValidar))
                    .Where(o => o.IdRuta == id)
                    .Single();

                if (oPE_Ruta == null)
                {
                    return HttpNotFound();
                }


                foreach (OPE_Visita visita in oPE_Ruta.OPE_Visita)
                {

                    if (visita.OPE_ServicioVisita != null)
                        foreach (OPE_ServicioVisita servicioVisita in visita.OPE_ServicioVisita)
                        {
                            if (string.IsNullOrEmpty(servicioVisita.RutaFotografia) && !string.IsNullOrEmpty(servicioVisita.CadenaFotografia))
                            {
                                servicioVisita.RutaFotografia = ConvierteBase64(servicioVisita.CadenaFotografia);
                                db.Entry(servicioVisita).State = EntityState.Modified;
                                db.SaveChanges();
                            }
                        }

                    if (visita.OPE_Devolucion != null)
                        foreach (OPE_Devolucion devolucion in visita.OPE_Devolucion)
                        {
                            if (string.IsNullOrEmpty(devolucion.RutaFotografia) && !string.IsNullOrEmpty(devolucion.CadenaFotografia))
                            {
                                devolucion.RutaFotografia = ConvierteBase64(devolucion.CadenaFotografia);
                                db.Entry(devolucion).State = EntityState.Modified;
                                db.SaveChanges();
                            }
                        }

                    if (visita.OPE_CheckOut != null)
                    {
                        if (string.IsNullOrEmpty(visita.OPE_CheckOut.RutaFotografiaAtras) && !string.IsNullOrEmpty(visita.OPE_CheckOut.CadenaFotografiaAtras))
                            visita.OPE_CheckOut.RutaFotografiaAtras = ConvierteBase64(visita.OPE_CheckOut.CadenaFotografiaAtras);

                        if (string.IsNullOrEmpty(visita.OPE_CheckOut.RutaFotografiaFrente) && !string.IsNullOrEmpty(visita.OPE_CheckOut.CadenaFotografiaFrente))
                            visita.OPE_CheckOut.RutaFotografiaFrente = ConvierteBase64(visita.OPE_CheckOut.CadenaFotografiaFrente);

                        if (string.IsNullOrEmpty(visita.OPE_CheckOut.RutaFotografiaLateralDerecho) && !string.IsNullOrEmpty(visita.OPE_CheckOut.CadenaFotografiaLateralDerecha))
                            visita.OPE_CheckOut.RutaFotografiaLateralDerecho = ConvierteBase64(visita.OPE_CheckOut.CadenaFotografiaLateralDerecha);

                        if (string.IsNullOrEmpty(visita.OPE_CheckOut.RutaFotografiaLateralIzquierda) && !string.IsNullOrEmpty(visita.OPE_CheckOut.CadenaFotografiaLateralIzquierda))
                            visita.OPE_CheckOut.RutaFotografiaLateralIzquierda = ConvierteBase64(visita.OPE_CheckOut.CadenaFotografiaLateralIzquierda);

                        if (string.IsNullOrEmpty(visita.OPE_CheckOut.RutaFirmaResponsable) && !string.IsNullOrEmpty(visita.OPE_CheckOut.CadenaFirmaResponsable))
                            visita.OPE_CheckOut.RutaFirmaResponsable = ConvierteBase64(visita.OPE_CheckOut.CadenaFirmaResponsable);

                        db.Entry(visita.OPE_CheckOut).State = EntityState.Modified;
                        db.SaveChanges();

                    }


                    if (visita.OPE_CheckOutSinValidar != null)
                    {
                        if (string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.RutaFotografiaAtras) && !string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.CadenaFotografiaAtras))
                            visita.OPE_CheckOutSinValidar.RutaFotografiaAtras = ConvierteBase64(visita.OPE_CheckOutSinValidar.CadenaFotografiaAtras);

                        if (string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.RutaFotografiaFrente) && !string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.CadenaFotografiaFrente))
                            visita.OPE_CheckOutSinValidar.RutaFotografiaFrente = ConvierteBase64(visita.OPE_CheckOutSinValidar.CadenaFotografiaFrente);

                        if (string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.RutaFotografiaLateralDerecho) && !string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.CadenaFotografiaLateralDerecha))
                            visita.OPE_CheckOutSinValidar.RutaFotografiaLateralDerecho = ConvierteBase64(visita.OPE_CheckOutSinValidar.CadenaFotografiaLateralDerecha);

                        if (string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.RutaFotografiaLateralIzquierda) && !string.IsNullOrEmpty(visita.OPE_CheckOutSinValidar.CadenaFotografiaLateralIzquierda))
                            visita.OPE_CheckOutSinValidar.RutaFotografiaLateralIzquierda = ConvierteBase64(visita.OPE_CheckOutSinValidar.CadenaFotografiaLateralIzquierda);


                        db.Entry(visita.OPE_CheckOutSinValidar).State = EntityState.Modified;
                        db.SaveChanges();

                    }

                }

            }
            catch (DbEntityValidationException ex)
            {
                foreach (DbEntityValidationResult item2 in ex.EntityValidationErrors)
                {
                    // Get entry

                    DbEntityEntry entry = item2.Entry;
                    string entityTypeName = entry.Entity.GetType().Name;

                    // Display or log error messages

                    foreach (DbValidationError subItem in item2.ValidationErrors)
                    {
                        string message = string.Format("Error '{0}' occurred in {1} at {2}",
                                 subItem.ErrorMessage, entityTypeName, subItem.PropertyName);
                        Console.WriteLine(message);
                    }
                }
            }

            return View(oPE_Ruta);
        }

        private string ConvierteBase64(string base64)
        {
            string ruta = string.Empty;
            string archivo = Guid.NewGuid().ToString("N");

            try
            {
                byte[] imageBytes = Convert.FromBase64String(base64);
                
                ruta = Path.Combine(Server.MapPath("~/Imagenes/"), string.Format("{0}.jpeg", archivo));

                using (var ms = new MemoryStream(imageBytes, 0, imageBytes.Length))
                {
                    Image image = Image.FromStream(ms, true);
                    image.Save(ruta, System.Drawing.Imaging.ImageFormat.Jpeg);

                }
            }
            catch (Exception ex)
            {
            }

            return ruta;

        }



        // GET: /Ruta/Create
        public ActionResult Create()
        {
            ViewBag.UsernameTecnico = new SelectList(db.CAT_Usuario.Where(m => m.Activo), "Username", "Nombre");
            Session["Listado"] = null;

            return View();
        }

        // POST: /Ruta/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OPE_Ruta oPE_Ruta)
        {
            List<OPE_Visita> listaVisita = null;

TotalService/Controllers/VisitadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TotalService.Models;

namespace TotalService.Controllers
{

   // [Authorize(Roles = Helpers.Comunes.ROL_Administrador + "," + Helpers.Comunes.ROL_Supervisor)]
    public class VisitadoController : Controller
    {
        private grocusmx_totalserviceEntities db = new grocusmx_totalserviceEntities();

        // GET: /Visitado/
        public ActionResult Index()
        {
            return View(db.OPE_Visitado.ToList());
        }

        // GET: /Visitado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPE_Visitado oPE_Visitado = db.OPE_Visitado.Find(id);
            if (oPE_Visitado == null)
            {
                return HttpNotFound();
            }
            return View(oPE_Visitado);
        }

        // GET: /Visitado/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Visitado/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="IdVisitado,NombreEmpresa,NombreResponsable,Direccion,Colonia,Municipio,Telefono,UsuarioCreacion,UsuarioUltimaModificacion,FechaCreacion,FechaUltimaModificacion")] OPE_Visitado oPE_Visitado)
        {
            if (ModelState.IsValid)
            {
                db.OPE_Visitado.Add(oPE_Visitado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(oPE_Visitado);
        }

        // GET: /Visitado/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPE_Visitado oPE_Visitado = db.OPE_Visitado.Find(id);
            if (oPE_Visitado == null)
            {
                return HttpNotFound();
            }
            return View(oPE_Visitado);
        }

        // POST: /Visitado/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="IdVisitado,NombreEmpresa,NombreResponsable,Direccion,Colonia,Municipio,Telefono,UsuarioCreacion,UsuarioUltimaModificacion,FechaCreacion,FechaUltimaModificacion")] OPE_Visitado oPE_Visitado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oPE_Visitado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(oPE_Visitado);
        }

        // GET: /Visitado/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OPE_Visitado oPE_Visitado = db.OPE_Visitado.Find(id);
            if (oPE_Visitado == null)
            {
                return HttpNotFound();
            }
            return View(oPE_Visitado);
        }

        // POST: /Visitado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OPE_Visitado oPE_Visitado = db.OPE_Visitado.Find(id);
            db.OPE_Visitado.Remove(oPE_Visitado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TotalService/Views/Ruta/Create.cshtml
@model TotalService.Models.OPE_Ruta

@{
    ViewBag.Title = "Alta de Ruta";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Alta de Ruta</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("Listado", "Index")
            </li>
            <li class="active">
                <strong>Alta de Ruta</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
            @Html.ActionLink("Mostrar todos", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>



<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Alta de Ruta</h5>
                </div>
                <div class="ibox-content">

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true)

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.UsernameTecnico, "Técnico", new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownListFor(model => model.UsernameTecnico, new SelectList(ViewBag.UsernameTecnico, "Value", "Text"), new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.UsernameTecnico)
                                        </div>
                                    </div>

                                    <div class="form-group" id="calFechaRuta">
                                        @Html.LabelFor(model => model.FechaRuta, new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">

                                            <div class="input-group date">
                                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                @Html.EditorFor(model => model.FechaRuta, new { @class = "form-comtrol" })

                                            </div>
                                            @Html.ValidationMessageFor(model => model.FechaRuta)
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Guardar" class="btn btn-primary" />
                                            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-white" })
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>


                    <div id="divVisitado"></div>

                    @using (Ajax.BeginForm("Visitado", "Ruta", new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", UpdateTargetId = "divVisitado" }))
                    {

                        @Html.Partial("_Visitado", new TotalService.Models.OPE_Visitado());
                    }



                </div>
            </div>
        </div>
    </div>
</div>



@section Styles {
    @Styles.Render("~/plugins/awesomeCheckboxStyles")
    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/switcheryStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/nouiSliderStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/Content/plugins/ionRangeSlider/ionRangeStyles")
    @Styles.Render("~/plugins/imagecropperStyles")
    @Styles.Render("~/Content/plugins/colorpicker/colorpickerStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/touchSpinStyles")
    @Styles.Render("~/plugins/tagInputsStyles")
    @Styles.Render("~/plugins/duallistStyles")
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/ionRange")
    @Scripts.Render("~/plugins/nouiSlider")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/switchery")
    @Scripts.Render("~/plugins/chosen")
    @Scripts.Render("~/plugins/knob")
    @Scripts.Render("~/plugins/imagecropper")
    @Scripts.Render("~/plugins/colorpicker")
    @Scripts.Render("~/plugins/clockpicker")
    @Scripts.Render("~/plugins/dateRange")
    @Scripts.Render("~/plugins/select2")
    @Scripts.Render("~/plugins/touchSpin")
    @Scripts.Render("~/plugins/tagInputs")
    @Scripts.Render("~/plugins/duallist")



    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $('#calF2echaRuta .input-group.date').datepicker({
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true,
                format: 'mm/dd/yyyy'
            });


        });
    </script>

}

TotalService/Views/Ruta/Edit.cshtml
@model TotalService.Models.OPE_Ruta

@{
    ViewBag.Title = "Editar Ruta";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-sm-4">
        <h2>Editar Ruta</h2>
        <ol class="breadcrumb">
            <li>
                @Html.ActionLink("Listado", "Index")
            </li>
            <li class="active">
                <strong>Editar Ruta</strong>
            </li>
        </ol>
    </div>
    <div class="col-sm-8">
        <div class="title-action">
			@Html.ActionLink("Mostrar todos", "Index", null, new { @class = "btn btn-primary"})
        </div>
    </div>
</div>




<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Editar Ruta</h5>
                </div>
                <div class="ibox-content">

				@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.IdRuta)

        <div class="form-group">
            @Html.Label("Usuario", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.UsernameTecnico, new SelectList(ViewBag.UsernameTecnico, "Value", "Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UsernameTecnico)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaRuta, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FechaRuta, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date" })
                @Html.ValidationMessageFor(model => model.FechaRuta)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
				@Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-white"})
            </div>
        </div>
    </div>
}

                    <div id="divVisitado">

                        @{
                            if (Model != null && Model.OPE_Visita != null)
                            {
                                Html.RenderPartial("_IndexVisitado", Model.OPE_Visita);
                            }
                        }

                    </div>

                    @using (Ajax.BeginForm("Visitado", "Ruta", new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", UpdateTargetId = "divVisitado" }))
                    {
                        @Html.Partial("_Visitado", new TotalService.Models.OPE_Visitado());
                    }


                </div>
            </div>
        </div>
    </div>
 </div>





@section Styles {
    @Styles.Render("~/plugins/awesomeCheckboxStyles")
    @Styles.Render("~/plugins/clockpickerStyles")
    @Styles.Render("~/plugins/dateRangeStyles")
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/Content/plugins/chosen/chosenStyles")
    @Styles.Render("~/plugins/switcheryStyles")
    @Styles.Render("~/plugins/jasnyBootstrapStyles")
    @Styles.Render("~/plugins/nouiSliderStyles")
    @Styles.Render("~/plugins/dataPickerStyles")
    @Styles.Render("~/Content/plugins/ionRangeSlider/ionRangeStyles")
    @Styles.Render("~/plugins/imagecropperStyles")
    @Styles.Render("~/Content/plugins/colorpicker/colorpickerStyles")
    @Styles.Render("~/plugins/select2Styles")
    @Styles.Render("~/plugins/touchSpinStyles")
    @Styles.Render("~/plugins/tagInputsStyles")
    @Styles.Render("~/plugins/duallistStyles")
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/dataPicker")
    @Scripts.Render("~/plugins/ionRange")
    @Scripts.Render("~/plugins/nouiSlider")
    @Scripts.Render("~/plugins/jasnyBootstrap")
    @Scripts.Render("~/plugins/switchery")
    @Scripts.Render("~/plugins/chosen")
    @Scripts.Render("~/plugins/knob")
    @Scripts.Render("~/plugins/imagecropper")
    @Scripts.Render("~/plugins/colorpicker")
    @Scripts.Render("~/plugins/clockpicker")
    @Scripts.Render("~/plugins/dateRange")
    @Scripts.Render("~/plugins/select2")
    @Scripts.Render("~/plugins/touchSpin")
    @Scripts.Render("~/plugins/tagInputs")
    @Scripts.Render("~/plugins/duallist")

<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>   
}

TotalService/Views/Ruta/_IndexDevolucion.cshtml
@model IEnumerable<TotalService.Models.OPE_Devolucion>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ComentarioDevolucion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DevolvioRefacciones)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CadenaFotografia)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ComentarioDevolucion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DevolvioRefacciones)
        </td>
        <td>
            <img src="@Url.Content("~/Imagenes/" + System.IO.Path.GetFileName(item.RutaFotografia))" />
        </td>
    </tr>
}

</table>

TotalService/Views/Ruta/_IndexVisitado.cshtml
@model IEnumerable<TotalService.Models.OPE_Visita>


@using (Ajax.BeginForm("EliminaVisitado", "Ruta", new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", UpdateTargetId = "divVisitado" }))
{
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">

                <input type="hidden" name="filaEliminar" id="filaEliminar" value=""/>

                <div class="ibox-content">

                    <table class="table table-striped">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.First().OPE_Visitado.NombreEmpresa)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.First().OPE_Visitado.NombreResponsable)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.First().OPE_Visitado.Direccion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.First().OPE_Visitado.Colonia)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.First().OPE_Visitado.Municipio)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.First().OPE_Visitado.Telefono)
                            </th>
                            <th></th>
                        </tr>
                        @{int indice = 0; }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.OPE_Visitado.NombreEmpresa)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OPE_Visitado.NombreResponsable)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OPE_Visitado.Direccion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OPE_Visitado.Colonia)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OPE_Visitado.Municipio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OPE_Visitado.Telefono)
                            </td>
                            <td>
                                @if (item.OPE_Visitado.Editable.Value)
                                {
                                <input type="submit" value="Eliminar" onclick="$('#filaEliminar').val( @indice )" class="btn btn-primary" />
                                }

                                @{ indice = indice + 1;  }
                            </td>
                        </tr>
                    }

                    </table>

                </div>
            </div>
        </div>
    </div>
 </div>


}